# Generated by Django 3.1.2 on 2020-11-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupletchatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
